server:
  port: 8082  #端口
  servlet:
    context-path: /springboot-demo    #项目链接默认路径
spring:
  mvc:
    static-path-pattern: /META-INF/resources/**  #静态资源存放路径
  thymeleaf:
    model: HTML #模板模式、默认为HTML5
    prefix: classpath:/META-INF/resources/  #自定义的Thymeleaf的模板位置，jar内部以classpath:开头，外部路径使用file:开头
    suffix: .html #模板后缀 默认为.html 自动匹配后缀
    cache: false #cache=是否使用缓存 默认true
