#spring boot 启动参数
server:
  port: 8085
  servlet:
    context-path: /activiti

spring:
  datasource:
    url: jdbc:mysql://110.42.174.215:53306/spring-boot-demo
    username: root
    password: root
    hikari:
      data-source-properties:
        useSSL: false
        serverTimezone: GMT+8
        useUnicode: true
        characterEncoding: utf8
        # 这个必须要加，否则 Activiti 自动建表会失败
        nullCatalogMeansCurrent: true
  activiti:
    #如果表不存在,则自动创建
    database-schema-update: true
    #保存历史数据的最高级别
    history-level: full
    #检测历史表是否存在
    db-history-used: true